apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieapp
  template:
    metadata:
      labels:
        app: movieapp
    spec:
      containers:
      - name: movieapp-container
        image: movieapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
