# Generated by Django 3.2.25 on 2025-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(max_length=100)),
                ('Actor2Name', models.CharField(blank=True, max_length=100)),
                ('DirectorName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror')], max_length=50)),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
    ]
